# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 030f475ad4f10becc3fc404a5d97b8bbe69e2bedac94ae83254490100d9f6b922d77597e5c38399c5cd5bcbb778ad9f96807404d6c0213ebbca50fe34f7365a9

test:
  secret_key_base: f0c1f84ad08b40a6c060b2bde94fec9c6b913d13c9d72f6b658bd90b58322bb5c3894ad249a84419e270e0f0a97a78e585ed32ff5dfd822ba4503cd8d5f6ff8a

staging:
  secret_key_base: ababffe6f0c1b6b647f9340c31db2c8994a3dd11d49fb3fc36f90f2fc5ba6b0bb0a4648c91819ffda31f1a45321c3b0ebc951fbe6c4413b758273a460e0a467f

# staging:
#   secret_key_base: 
#   ababffe6f0c1b6b647f9340c31db2c8994a3dd11d49fb3fc36f90f2fc5ba6b0bb0a4648c91819ffda31f1a45321c3b0ebc951fbe6c4413b758273a460e0a467f

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
